# Generated by Django 3.1.2 on 2021-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210819_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='language',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='service_type',
            field=models.CharField(blank=True, choices=[('D', 'Driving'), ('F', 'Flying'), ('W', 'Walking'), ('C', 'Cycling'), ('R', 'Running'), ('B', 'Boating'), ('O', 'Other')], max_length=3000, null=True),
        ),
    ]
