# Generated by Django 3.1.2 on 2021-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20210819_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
