# Generated by Django 3.1.2 on 2021-08-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
